[application]
host = "127.0.0.1"
port = 8000

[database]
host = "127.0.0.1"
port = 5432
username = "postgres"
password = "password"
name = "newsletter"

[email_client]
base_url = "http://localhost"
sender_email = "test@gmail.com"
auth_token = "my-secret-token"
